const mongoose = require('mongoose');

const CommunicationLogSchema = new mongoose.Schema({
  campaignId: { type: mongoose.Schema.Types.ObjectId, ref: 'Campaign', required: true },
  customerId: { type: mongoose.Schema.Types.ObjectId, ref: 'Customer', required: true },
  // WHY: messageId is a UUID generated by CRM — it's what ties the stub's callback
  // back to this specific log entry without exposing internal MongoDB IDs externally
  messageId: { type: String, required: true, unique: true },
  channel: { type: String },
  status: {
    type: String,
    enum: ['sent', 'delivered', 'failed', 'opened', 'clicked'],
    default: 'sent',
  },
  timestamps: {
    sent: Date,
    delivered: Date,
    failed: Date,
    opened: Date,
    clicked: Date,
  },
}, { timestamps: true });

module.exports = mongoose.model('CommunicationLog', CommunicationLogSchema);
